### ISSUE TITLE
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

### ISSUE THREAD

**Issue by qjayforever25** [qjayforever25/Qjayforever25#1]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Run tox or thefuck.

## What happened (include command output)

I tried to run tox after upgrading and it seems that the symlinks are broken to both tox and thefuck.

<details>
  <summary>Command output</summary>
  <pre>
   tox
  /home/linuxbrew/.linuxbrew/Cellar/tox/3.14.6/libexec/bin/python3.8: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

  </pre>
</details>

## What you expected to happen

tox should work

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install tox
brew upgrade
tox

_Originally posted by @thedrow in https://github.com/Homebrew/linuxbrew-core/issues/20174_
